### ISSUE TITLE
statusreport-period = 0 in config.toml seems not working

### ISSUE THREAD

**Issue by sraue** [threathunters-io/laurel#107] opened 2022-11-21 08:43 UTC
Hi,

setting statusreport-period = 0 in config.toml seems not to disable the status reports in version 0.4.1. instead it spams syslog several times per second with the status report. older versions i dont have tested.

greetings, Stephan

**Comment by disasmwinnie** [comment] 2022-11-21 14:28
Can reproduce.

the problem is here: https://github.com/threathunters-io/laurel/blob/5bc800a9d291945d88188fabb07ccf9a2346fb10/src/main.rs#L296

A check if the config param is > 0 should fix the issue.

**Comment by hillu** [comment] 2022-11-23 18:52
Fix merged.

**Closed by hillu** 2022-11-23 18:52 UTC
