### ISSUE TITLE
Trouble Installing on CentOS/RedHat 7

### ISSUE THREAD

**Issue by ZRAMTEST** [threathunters-io/laurel#71] opened 2022-01-31 17:03 UTC
I am getting various errors when trying to build Laurel and have tried the following to resolve them yet to no avail. Am I doing something wrong or is this not supported for CentOS/RedHat 7? Would anyone kindly also provide details concerning the "…or use the provided binary" section aswell? I am by no means an expert in Rust and have recently started working with auditd logs, all and any help is greatly appreciated.

**1st Error:**
```
rustc_codegen_ssa::back::link Linker does not support -no-pie command line option. Retrying without.
error: failed to run custom build command for `laurel v0.2.2 (/root/laurel)`

Caused by:
  process didn't exit successfully: `/root/laurel/target/release/build/laurel-539ef58d19694a47/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'Unable to find libclang: "couldn't find any valid shared libraries matching: ['libclang.so', 'libclang-*.so', 'libclang.so.*', 'libclang-*.so.*'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.59.2/src/lib.rs:2144:31
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**1st Error resolved by the following commands:**

```
yum install libclang*
rpm -qa | grep "llvm-private"
rpm -e --nodeps llvm-private-7.0.1-1.el7.x86_64
sudo yum groupinstall "Development tools"
```

**2nd Error which I got stuck in:**
```
Caused by:
  process didn't exit successfully: `/root/laurel/target/release/build/laurel-539ef58d19694a47/build-script-build` (exit status: 101)
  --- stderr
  /usr/include/linux/if_pppol2tp.h:29:21: error: field has incomplete type 'struct sockaddr_in'
  /usr/include/linux/if_pppol2tp.h:29:9: note: forward declaration of 'struct sockaddr_in'
  /usr/include/linux/if_pppol2tp.h:46:22: error: field has incomplete type 'struct sockaddr_in6'
  /usr/include/linux/if_pppol2tp.h:46:9: note: forward declaration of 'struct sockaddr_in6'
  /usr/include/linux/if_pppol2tp.h:57:21: error: field has incomplete type 'struct sockaddr_in'
  /usr/include/linux/if_pppol2tp.h:29:9: note: forward declaration of 'struct sockaddr_in'
  /usr/include/linux/if_pppol2tp.h:71:22: error: field has incomplete type 'struct sockaddr_in6'
  /usr/include/linux/if_pppol2tp.h:46:9: note: forward declaration of 'struct sockaddr_in6'
  /usr/include/linux/if_pppox.h:42:20: error: use of undeclared identifier 'IFNAMSIZ'
  /usr/include/linux/if_pppox.h:50:17: error: field has incomplete type 'struct in_addr'
  /usr/include/linux/if_pppox.h:50:9: note: forward declaration of 'struct in_addr'
  src/sockaddr.h:12:10: fatal error: 'linux/if_xdp.h' file not found
  /usr/include/linux/if_pppol2tp.h:29:21: error: field has incomplete type 'struct sockaddr_in', err: true
  /usr/include/linux/if_pppol2tp.h:46:22: error: field has incomplete type 'struct sockaddr_in6', err: true
  /usr/include/linux/if_pppol2tp.h:57:21: error: field has incomplete type 'struct sockaddr_in', err: true
  /usr/include/linux/if_pppol2tp.h:71:22: error: field has incomplete type 'struct sockaddr_in6', err: true
  /usr/include/linux/if_pppox.h:42:20: error: use of undeclared identifier 'IFNAMSIZ', err: true
  /usr/include/linux/if_pppox.h:50:17: error: field has incomplete type 'struct in_addr', err: true
  src/sockaddr.h:12:10: fatal error: 'linux/if_xdp.h' file not found, err: true
  thread 'main' panicked at 'unable to generate bindings: ()', build.rs:113:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by hillu** [comment] 2022-05-29 08:11
Could you please try again using the latest commit?

**Comment by hillu** [comment] 2022-06-20 09:14
@ZRAMTEST Have you been able to reproduce the problem with more rercent commits / versions?

**Comment by hillu** [comment] 2022-07-08 10:04
@ZRAMTEST ping?

**Comment by hillu** [comment] 2022-08-01 09:51
@ZRAMTEST ping?

**Comment by hillu** [comment] 2022-08-22 09:54
@ZRAMTEST I am sorry, since you haven't provided any information, I'm not able to help you and am closing this issue.

If you should change your mind, feel free to reopen this issue.

**Closed by hillu** 2022-08-22 09:54 UTC
