### ISSUE TITLE
Service auditd "rotate"

### ISSUE THREAD

**Issue by grumo35** [threathunters-io/laurel#159] opened 2023-07-27 08:44 UTC
Hello,

Using the built-in "service auditd rotate" i got the following error

`juil. 27 10:37:51 Server auditd[44909]: Couldn't change permissions while rotating log file (Bad file descriptor)
juil. 27 10:37:51 Server auditd[44909]: Couldn't change ownership while rotating log file (Bad file descriptor)
juil. 27 10:37:51 Server systemd[1]: auditd.service: Main process exited, code=killed, status=11/SEGV
juil. 27 10:37:51 Server /usr/local/sbin/laurel[44911]: Stopped /usr/local/sbin/laurel processed 5897 lines 0 events with 2 errors in total
juil. 27 10:37:51 Server systemd[1]: auditd.service: Failed with result 'signal'.
`

My understanding is that auditd restore is somewhat looking for normal auditd permissions without laurel depsite the config file mentionning the _laurel ownership.

Is it something you are aware of ?

**Comment by disasmwinnie** [comment] 2023-07-27 09:19
Hello @grumo35, 

I don't think the issue is related to Laurel. Reading the error message it simply says that Auditd was killed and the Laurel process with it. Which makes sense since it's a plugin respectively a process started by Auditd.

The reason for killing Auditd, seems to be a permission problem with Auditd log "files". While Laurel gets the event from the Auditd Multiplexer Audisp (via stdin), it does not touch the log "files" of the original Audit Daemon. I hope the explanation makes sense...

My best guess is, that permissions for ``/var/log/audit/`` and/or its contents do not match (anymore) the ``log_group`` parameter in ``auditd.conf``.

**Comment by hillu** [comment] 2023-07-27 22:08
@grumo35 what distribution are you using? I must say I haven't seen `service auditd rotate` being used before.

**Comment by hillu** [comment] 2023-09-19 23:25
@grumo35 ping?

**Comment by hillu** [comment] 2023-11-07 22:38
@grumo35 ping?

**Comment by hillu** [comment] 2023-11-20 20:11
@grumo35 I'm closing this issue since you can't be bothered to assist in reproducing your problem by answering simple questions.

**Closed by hillu** 2023-11-20 20:11 UTC

**Comment by grumo35** [comment] 2024-10-22 14:01
I'm using debian, sorry for latency i wasnt paying attention. I definetly think it was some miss configurations on my end.

**Comment by hillu** [comment] 2024-10-22 16:42
@grumo35 Welcome back!
The error messages you originally posted ("Couldn't change permissions", "Couldn't change ownership") are produced by auditd, not by Laurel. Laurel should write its logs into a separate directory, `/var/log/laurel` by default.
Does the problem still persist?

**Comment by hillu** [comment] 2024-10-28 08:39
@grumo35 ping?

**Comment by grumo35** [comment] 2024-10-30 17:47
The problem is solved, it was a missconfiguration of ownership, as you precised with auditd / laurel separate writings ! thanks for following up

**Comment by hillu** [comment] 2024-10-30 19:41
@grumo35 Alright, thanks.
